spring.application.name=finance
spring.datasource.url=jdbc:mysql://localhost:3306/finance_db
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jwt.secret=7y$kR92N!mPzQ5vX8*uWbE4tA1sL#oGj
spring.jwt.expiration=1800000